services:
  db: 
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  db-test: 
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5433:5432
